# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0811410556eed4173798eb426310a94b57a3f83d80d07b0defb6aeba60f33f2596c20599b56e01956e8f145da51e797a9d975517f27ab0c7c15cc9cfeddcee61
  facebook_app_id: 540017629511990
  facebook_app_secret: bc8fd9360015f3232137a35b4aaf8ce1
  twitter_app_id: 1Dc1jQIUiNW7D4CAeT8VhFJUK
  twitter_app_secret: JLBydUCXpB6MzH7npW75WIYRtUw8ibGCQ7KQyb89ixhfYsSL40
  vkontakte_app_id: 5234799
  vkontakte_app_secret: HPjn0vIy7iVwUpMkLKtO

test:
  secret_key_base: 6359ed1cade27f0d3b7948dd02c06c3500ca4595036dafc650f9169cbbbba6467ae52964a41523555dae2a6d77e04cf661828f7037325bbf28a4a004fd267eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
